---
version: "2.0"
services:
  master-node:
    image: a2nfinance/detrain-nodes:0.2.2
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
      - port: 9999
        as: 9999
        proto: tcp
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - uvicorn main:app --host 0.0.0.0 --port 5000;sleep infinity
profiles:
  compute:
    master-node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4GB
        storage:
          - size: 20GB
  placement:
    dcloud:
      pricing:
        master-node:
          denom: uakt
          amount: 1000
deployment:
  master-node:
    dcloud:
      profile: master-node
      count: 1
