---
version: "2.0"
services:
  detrain-servers:
    image: pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 9999
        as: 9999
        accept:
          - 0.0.0.0/0
        proto: tcp
        to:
          - global: true
    command:
      - apt-get
      - install
      - git;pip
      - install
      - fastapi;pip
      - install
      - fastapi;pip
      - install
      - "\"uvicorn[standard]\""
      - gunicorn;pip
      - install
      - detrain;git
      - clone
      - https://github.com/a2nfinance/detrain
      - /mnt/data/detrain;python3
      - /mnt/data/detrain/agent/main.py
    args:
      - ""
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
profiles:
  compute:
    detrain-servers:
      resources:
        cpu:
          units: 1
        memory:
          size: 1GB
        storage:
          - size: 1Gi
          - name: data
            size: 15Gi
            attributes:
              persistent: true
              class: beta2
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: p100
                  ram: 16Gi
                  interface: pcie
  placement:
    dcloud:
      pricing:
        detrain-servers:
          denom: uakt
          amount: 1000
deployment:
  detrain-servers:
    dcloud:
      profile: detrain-servers
      count: 2
