---
version: "2.0"
services:
  service-1:
    image: pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    command:
      - systemctl
      - daemon-reload;systemctl
      - start
      - detrain_agent.service
    args:
      - ""
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 1GB
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta2
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
                  ram: 40Gi
                  interface: pcie
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
