---
version: "2.0"
services:
  node-rank-0:
    image: a2nfinance/detrain-nodes:0.2.2
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
      - port: 9999
        as: 9999
        accept:
          - 0.0.0.0/0
        proto: tcp
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - uvicorn main:app --host 0.0.0.0 --port 5000;sleep infinity
  node-rank-1:
    image: a2nfinance/detrain-nodes:0.2.2
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
      - port: 9999
        as: 9999
        accept:
          - 0.0.0.0/0
        proto: tcp
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - uvicorn main:app --host 0.0.0.0 --port 5000;sleep infinity
profiles:
  compute:
    node-rank-0:
      resources:
        cpu:
          units: 2
        memory:
          size: 4GB
        storage:
          - size: 20GB
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
    node-rank-1:
      resources:
        cpu:
          units: 2
        memory:
          size: 4GB
        storage:
          - size: 20GB
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    dcloud:
      pricing:
        node-rank-0:
          denom: uakt
          amount: 1000
        node-rank-1:
          denom: uakt
          amount: 1000
deployment:
  node-rank-0:
    dcloud:
      profile: node-rank-0
      count: 1
  node-rank-1:
    dcloud:
      profile: node-rank-1
      count: 1
